apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  containers:
    - name: volume-container-datacenter-1
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - mountPath: "/tmp/news"
          name: volume-share
    - name: volume-container-datacenter-2
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]     
      volumeMounts:
        - mountPath: "/tmp/news"
          name: volume-share
  volumes:
    - name: volume-share
      emptyDir: {}
